### ISSUE TITLE
Define comparison between 1609 and 1623 encoding

### ISSUE THREAD

**Issue by tiagosousagarcia** [NewcastleRSE/beeing-human-tei-data#23]
### Summary

*Define how comparisons between 1609 and 1623 should be made in the encoding. The running concept would be to use `<app>` with `<lem>` and `<rdg>`. See [the Guidelines for more.](https://tei-c.org/release/doc/tei-p5-doc/en/html/TC.html)*

#### Concept
All changes will be marked on 1623, and will follow the [parallel segmentation method](https://tei-c.org/release/doc/tei-p5-doc/en/html/TC.html#TCAPPS), with the difference that instead of copying the text from 1609, it will be marked by pointers that will be replaced at a later stage by the text. The changes can be spans of arbitrary length (from a few characters to whole paragraphs). Any change that is more granular than a paragraph will be marked with two milestone elements (`anchor` with a required `@xml:id`) in 1609, and that span will then be used to indicate the 1609 text in 1623. Changes that span more than one paragraph or that break other tags will themselves need to be marked with `anchor` and using standoff methods -- however, these will not be defined until later, if needed. A script will then be used to replace the `@xml:id` of the differences of 1609 with the actual text. This will be done automatically, through a github actions, and produce a new consolidated file that will be displayed by the app. This should help keep 1609 and 1623 readable, while allowing the display in the app to only read one file, simplifying any transformations on that side.
##### Example:

1609:
```
The later part of which saying although the delicat Silk-worme have <anchor xml:id="ex1"/>else-where 
disproved, and is now setting foot in this land, here also to except against it; yet must shee needs 
confesse the former, and, when shee is come, yeelde the precedence to the laborious Bee, as to hir 
elder sister; which as in time, so in vertue is before her.<anchor xml:id="ex2"/> For the fruite of the 
Silke-worme serveth onlie to cover the bodie;
```

1623:
```
The later part of which saying, although the delicate Silk-worme have 
<app>
  <lem wit="1623">
        in some hoter Climates disproved; (for in the colder countries, such as is our Iland of 
        <placeName rend="italic">Britaine</placeName>, I doubt mee shee will never quit cost: and 
        therefore is here to be entertained only of them, that doe more respect their pleasure, than 
        their profit; and doe content themselves with the beholding of their queint worke, not expecting 
        any further recompence for their expence and paines;) yet mustshee needs confesse the former, 
        and wheresoever she meet the ingenuous and laborious Bee, yeeld the precendence to her, as to 
        hir Better.
  </lem>
  <rdg wit="1609"><link target="1609.xml#ex1 1609.xml#ex2"/></rdg>
</app>
For the fruite of the Silk-worme serveth onlie to cover the body;
```

Consolidated file (for display in the app):
```
The later part of which saying, although the delicate Silk-worme have 
<app>
  <lem wit="1623">
        in some hoter Climates disproved; (for in the colder countries, such as is our Iland of 
        <placeName rend="italic">Britaine</placeName>, I doubt mee shee will never quit cost: and 
        therefore is here to be entertained only of them, that doe more respect their pleasure, than 
        their profit; and doe content themselves with the beholding of their queint worke, not expecting 
        any further recompence for their expence and paines;) yet mustshee needs confesse the former, 
        and wheresoever she meet the ingenuous and laborious Bee, yeeld the precendence to her, as to 
        hir Better.
  </lem>
  <rdg wit="1609">
    else-where disproved, and is now setting foot in this land, here also to except against it; 
    yet must shee needs confesse the former, and, when shee is come, yeelde the precedence 
    to the laborious Bee, as to hir elder sister; which as in time, so in vertue is before her.
  </rdg>
</app>
For the fruite of the Silk-worme serveth onlie to cover the body;
```

### What needs to be done?

- [x] *Define how to encode this*
    - Types of differences:
        - [x] Like for like change (different spellings, different vocabulary, corrections)
        - [x] Deletions from 1609
        - [x] Additions to 1609
        - [x] Text reorganisation (see #32 )
- [x] *Add it to the customisation*
- [x] *Add it to the documentation*

---

### Updates

- 20231013 - 177d44b - added to the documentation and found examples for like for like change and deletions
- 20231011 - bfd018f and previous commits -- added necessary elements to the encoding, created witness lists, added anchor elements to the 1609 customisation, added to inline documentation of anchor in 1609, added encodingDesc and variantEncoding to header. TO DO: documentation on the ODD, examples, typology of apps, examples of each typology

**Comment by jamescummings** [comment]
You might not need to have `<link/>` as an element here, you could potentially use the `<ptr/>` element instead. I guess I'm thinking that what link means is that there are these two separate objects and A is linked somehow to B, whereas what you are saying is that **from** A to B is this witness' variant text. 

It is almost like you really would prefer to have the `@from`  (and possibly `@to` though you only need one really) attribute on `<rdg/>`? That might be a useful feature request to https://github.com/TEIC/TEI/issues

**Comment by tiagosousagarcia** [comment]
Thanks @jamescummings  -- indeed, `@from` `@to` in `<rdg>` was exactly what I was looking for (having a `@to` just makes it more readable and easier for processing later on, IMO).
Cool, so `<ptr/>` instead of `<link/>` -- this might be a little too pernickity, but would you say two pointers (i.e., `<ptr target="#start"/><ptr target="end"/>` or a single pointer with two targets (`<ptr target="#start #end"/>`)?

**Comment by jamescummings** [comment]
I'd have done a `<ptr/>` with two values in the `@target`.
