### ISSUE TITLE
<app> categories

### ISSUE THREAD

**Issue by OliviaFS** [NewcastleRSE/beeing-human-tei-data#59]
**Is your feature request related to a problem? Please describe.**
It might be helpful to have a specific app label for references? Some of the added text is bibliographic references and it felt like a different category of addition. I can wait and see as I move through the chapters. 

**Describe the solution you'd like**
To consider more varied labels. 

**Describe alternatives you've considered**
Just to mark it as substantive add with a anchor/ptr, like other types of addition.

**Additional context**
Depends what you think! Or maybe it depends on how many I aggregate. It also might be useful for chapter 10.

**Comment by tiagosousagarcia** [comment]
After a zoom discussion, @OliviaFS decided on a new typology:
- major - big changes to the main text
- minor - small changes to the main text
- orthographic - as it was before
- vocabulary - as it was before
- reference - changes that only add, delete or change references
- other - anything not currently covered.

@tiagosousagarcia will:
- review current changes and merge to dev tomorrow (16/11/2023)
- create new typology + documentation
- merge new typology + documentation to dev
- think about a way of previewing changes in display mode

@OliviaFS:
 - Write a small reflection on the types of changes encompassed by the new typology (to be included in docs / paratexts later on)
 - review variation in ch2
 - review typology of variation in ch1 and ch2 (once the new typology has been merged)
 
Other things to note:
- Good idea to have a big meeting about halfway through encoding the variation (after ch5), to check any changes that might need to be made to the process, pacing, priorities, etc.
- Ch2 contains a bit of editing and textual movement (see #32 ) -- will hold off on doing any more detailed encoding of this until half-way review meeting

**Comment by OliviaFS** [comment]
This is great. I've run into a few problems with the preview, which I've detailed in email. I'm getting unsure about making other changes because odd files keep appearing in my staging box... I need to get it ironed back out so that I can do these two things simultaneously. Thanks, let's speak tomorrow (17th).

**Comment by tiagosousagarcia** [comment]
closed by #71
