### ISSUE TITLE
Corrections to comparison in chapter 1

### ISSUE THREAD

**Issue by tiagosousagarcia** [NewcastleRSE/beeing-human-tei-data#60]
**Describe the bug**
@jr970 identified the following mistakes:

- [x] B1r - 1609 title: there should be a gap between due and ordering
- [x] B2r - para or point no. 7.  On the 1609 quote in Github I couldn't find the last four words 'and of their Queene.' in the copy of 1609.
    - _Anchor set 7 is entirely contained by anchor set 6 -- just looking at the code, it seems to me set 6 should break at the end of the page, and 7 should begin at the start of the next one. If 7 is a different type of change, then it should follow 6, rather than nesting in 6. @OliviaFS can you have a look at that?_
- [ ] B2r - the para, titled in the margin A memorable experiment, has quote marks in the margin: an important design feature we should ideally record.
    - _We can easily record that in the encoding, but re-creating it in the display version is a little more tricky (the text will break differently depending on screen that is used) -- I'll create a new issue to deal with that and look at it a little later - @tiagosousagarcia: see #63_ 
- [x] The like for like change proposed for para 40 looks exactly the same in both editions. I don't think the hover gives us the alternative passage from 1609, which I have pasted below:
    _- I have that change appearing correctly, see the screenshot below:_
![ch1sumn40](https://github.com/NewcastleRSE/beeing-human-tei-data/assets/29146428/2ba9d96a-a179-4d15-885d-6a0aa26437da)
- [x] C4v - a mightie needs to be followed with a comma (a mightie, ) This makes sense of the revised line.
    _- Corrected in the encoding, but in displaying an additional whitespace is added -- will correct that once we have a more established design. See #64_
- [x] D2v (para 53) - the first red highlight, when I hover is readers 'Does not exists in 1609' but it is not clear what.

**Comment by OliviaFS** [comment]
Ok I think I've worked out what's going on

**Comment by OliviaFS** [comment]
Can I delete my branch yet?

**Comment by tiagosousagarcia** [comment]
@OliviaFS have you finished making the correction? you need to make a pull request if so
