### ISSUE TITLE
Review typology of variation

### ISSUE THREAD

**Issue by tiagosousagarcia** [NewcastleRSE/beeing-human-tei-data#68]
### Summary

*Review the current `<app>` `@type` to follow the typology decided in #59:*
- major - big changes to the main text
- minor - small changes to the main text
- orthographic - as it was before
- vocabulary - as it was before
- reference - changes that only add, delete or change references
- other - anything not currently covered.

### What needs to be done?

- [x] *Update ODD*
- [x] *Update docs*

**Comment by OliviaFS** [comment]
This sounds really good, thanks
